# Databricks notebook source
# =============================================================================
# Apex F1 — 서킷 시드 데이터 → Supabase 적재
# =============================================================================
# 실행: Databricks에서 실행하거나, Supabase SQL Editor에 INSERT문으로 직접 실행
# =============================================================================

# MAGIC %run ../config

# COMMAND ----------

# 2024 시즌 서킷 데이터 (OpenF1 circuit_key 기준)
# circuit_key는 OpenF1 sessions API에서 반환하는 값과 매칭됨
circuits_data = [
    {
        "circuit_key": 61,
        "circuit_short_name": "Sakhir",
        "circuit_full_name": "Bahrain International Circuit",
        "country_name": "Bahrain",
        "country_code": "BHR",
        "city": "Sakhir",
        "track_length_km": 5.412,
        "turns": 15,
        "drs_zones": 3,
        "first_gp_year": 2004,
        "lap_record_time": "1:31.447",
        "lap_record_driver": "Pedro de la Rosa",
        "lap_record_year": 2005,
        "latitude": 26.0325,
        "longitude": 50.5106,
    },
    {
        "circuit_key": 62,
        "circuit_short_name": "Jeddah",
        "circuit_full_name": "Jeddah Corniche Circuit",
        "country_name": "Saudi Arabia",
        "country_code": "KSA",
        "city": "Jeddah",
        "track_length_km": 6.174,
        "turns": 27,
        "drs_zones": 3,
        "first_gp_year": 2021,
        "lap_record_time": "1:30.734",
        "lap_record_driver": "Lewis Hamilton",
        "lap_record_year": 2021,
        "latitude": 21.6319,
        "longitude": 39.1044,
    },
    {
        "circuit_key": 1,
        "circuit_short_name": "Melbourne",
        "circuit_full_name": "Albert Park Circuit",
        "country_name": "Australia",
        "country_code": "AUS",
        "city": "Melbourne",
        "track_length_km": 5.278,
        "turns": 14,
        "drs_zones": 4,
        "first_gp_year": 1996,
        "lap_record_time": "1:19.813",
        "lap_record_driver": "Charles Leclerc",
        "lap_record_year": 2024,
        "latitude": -37.8497,
        "longitude": 144.9680,
    },
    {
        "circuit_key": 63,
        "circuit_short_name": "Suzuka",
        "circuit_full_name": "Suzuka International Racing Course",
        "country_name": "Japan",
        "country_code": "JPN",
        "city": "Suzuka",
        "track_length_km": 5.807,
        "turns": 18,
        "drs_zones": 2,
        "first_gp_year": 1987,
        "lap_record_time": "1:30.983",
        "lap_record_driver": "Lewis Hamilton",
        "lap_record_year": 2019,
        "latitude": 34.8431,
        "longitude": 136.5406,
    },
    {
        "circuit_key": 2,
        "circuit_short_name": "Shanghai",
        "circuit_full_name": "Shanghai International Circuit",
        "country_name": "China",
        "country_code": "CHN",
        "city": "Shanghai",
        "track_length_km": 5.451,
        "turns": 16,
        "drs_zones": 2,
        "first_gp_year": 2004,
        "lap_record_time": "1:32.238",
        "lap_record_driver": "Michael Schumacher",
        "lap_record_year": 2004,
        "latitude": 31.3389,
        "longitude": 121.2197,
    },
    {
        "circuit_key": 3,
        "circuit_short_name": "Miami",
        "circuit_full_name": "Miami International Autodrome",
        "country_name": "United States",
        "country_code": "USA",
        "city": "Miami Gardens",
        "track_length_km": 5.412,
        "turns": 19,
        "drs_zones": 3,
        "first_gp_year": 2022,
        "lap_record_time": "1:29.708",
        "lap_record_driver": "Max Verstappen",
        "lap_record_year": 2023,
        "latitude": 25.9581,
        "longitude": -80.2389,
    },
    {
        "circuit_key": 4,
        "circuit_short_name": "Imola",
        "circuit_full_name": "Autodromo Enzo e Dino Ferrari",
        "country_name": "Italy",
        "country_code": "ITA",
        "city": "Imola",
        "track_length_km": 4.909,
        "turns": 19,
        "drs_zones": 2,
        "first_gp_year": 1980,
        "lap_record_time": "1:15.484",
        "lap_record_driver": "Lewis Hamilton",
        "lap_record_year": 2020,
        "latitude": 44.3439,
        "longitude": 11.7167,
    },
    {
        "circuit_key": 5,
        "circuit_short_name": "Monaco",
        "circuit_full_name": "Circuit de Monaco",
        "country_name": "Monaco",
        "country_code": "MON",
        "city": "Monte Carlo",
        "track_length_km": 3.337,
        "turns": 19,
        "drs_zones": 1,
        "first_gp_year": 1950,
        "lap_record_time": "1:12.909",
        "lap_record_driver": "Lewis Hamilton",
        "lap_record_year": 2021,
        "latitude": 43.7347,
        "longitude": 7.4206,
    },
    {
        "circuit_key": 6,
        "circuit_short_name": "Montreal",
        "circuit_full_name": "Circuit Gilles Villeneuve",
        "country_name": "Canada",
        "country_code": "CAN",
        "city": "Montreal",
        "track_length_km": 4.361,
        "turns": 14,
        "drs_zones": 2,
        "first_gp_year": 1978,
        "lap_record_time": "1:13.078",
        "lap_record_driver": "Valtteri Bottas",
        "lap_record_year": 2019,
        "latitude": 45.5000,
        "longitude": -73.5228,
    },
    {
        "circuit_key": 7,
        "circuit_short_name": "Barcelona",
        "circuit_full_name": "Circuit de Barcelona-Catalunya",
        "country_name": "Spain",
        "country_code": "ESP",
        "city": "Montmelo",
        "track_length_km": 4.657,
        "turns": 16,
        "drs_zones": 2,
        "first_gp_year": 1991,
        "lap_record_time": "1:16.330",
        "lap_record_driver": "Max Verstappen",
        "lap_record_year": 2023,
        "latitude": 41.5700,
        "longitude": 2.2611,
    },
    {
        "circuit_key": 8,
        "circuit_short_name": "Spielberg",
        "circuit_full_name": "Red Bull Ring",
        "country_name": "Austria",
        "country_code": "AUT",
        "city": "Spielberg",
        "track_length_km": 4.318,
        "turns": 10,
        "drs_zones": 3,
        "first_gp_year": 1970,
        "lap_record_time": "1:05.619",
        "lap_record_driver": "Carlos Sainz",
        "lap_record_year": 2020,
        "latitude": 47.2197,
        "longitude": 14.7647,
    },
    {
        "circuit_key": 9,
        "circuit_short_name": "Silverstone",
        "circuit_full_name": "Silverstone Circuit",
        "country_name": "Great Britain",
        "country_code": "GBR",
        "city": "Silverstone",
        "track_length_km": 5.891,
        "turns": 18,
        "drs_zones": 2,
        "first_gp_year": 1950,
        "lap_record_time": "1:27.097",
        "lap_record_driver": "Max Verstappen",
        "lap_record_year": 2020,
        "latitude": 52.0786,
        "longitude": -1.0169,
    },
    {
        "circuit_key": 10,
        "circuit_short_name": "Hungaroring",
        "circuit_full_name": "Hungaroring",
        "country_name": "Hungary",
        "country_code": "HUN",
        "city": "Budapest",
        "track_length_km": 4.381,
        "turns": 14,
        "drs_zones": 2,
        "first_gp_year": 1986,
        "lap_record_time": "1:16.627",
        "lap_record_driver": "Lewis Hamilton",
        "lap_record_year": 2020,
        "latitude": 47.5789,
        "longitude": 19.2486,
    },
    {
        "circuit_key": 11,
        "circuit_short_name": "Spa-Francorchamps",
        "circuit_full_name": "Circuit de Spa-Francorchamps",
        "country_name": "Belgium",
        "country_code": "BEL",
        "city": "Stavelot",
        "track_length_km": 7.004,
        "turns": 19,
        "drs_zones": 2,
        "first_gp_year": 1950,
        "lap_record_time": "1:46.286",
        "lap_record_driver": "Valtteri Bottas",
        "lap_record_year": 2018,
        "latitude": 50.4372,
        "longitude": 5.9714,
    },
    {
        "circuit_key": 12,
        "circuit_short_name": "Zandvoort",
        "circuit_full_name": "Circuit Zandvoort",
        "country_name": "Netherlands",
        "country_code": "NED",
        "city": "Zandvoort",
        "track_length_km": 4.259,
        "turns": 14,
        "drs_zones": 2,
        "first_gp_year": 1952,
        "lap_record_time": "1:11.097",
        "lap_record_driver": "Lewis Hamilton",
        "lap_record_year": 2021,
        "latitude": 52.3888,
        "longitude": 4.5409,
    },
    {
        "circuit_key": 13,
        "circuit_short_name": "Monza",
        "circuit_full_name": "Autodromo Nazionale Monza",
        "country_name": "Italy",
        "country_code": "ITA",
        "city": "Monza",
        "track_length_km": 5.793,
        "turns": 11,
        "drs_zones": 2,
        "first_gp_year": 1950,
        "lap_record_time": "1:21.046",
        "lap_record_driver": "Rubens Barrichello",
        "lap_record_year": 2004,
        "latitude": 45.6156,
        "longitude": 9.2811,
    },
    {
        "circuit_key": 14,
        "circuit_short_name": "Baku",
        "circuit_full_name": "Baku City Circuit",
        "country_name": "Azerbaijan",
        "country_code": "AZE",
        "city": "Baku",
        "track_length_km": 6.003,
        "turns": 20,
        "drs_zones": 2,
        "first_gp_year": 2016,
        "lap_record_time": "1:43.009",
        "lap_record_driver": "Charles Leclerc",
        "lap_record_year": 2019,
        "latitude": 40.3725,
        "longitude": 49.8533,
    },
    {
        "circuit_key": 15,
        "circuit_short_name": "Singapore",
        "circuit_full_name": "Marina Bay Street Circuit",
        "country_name": "Singapore",
        "country_code": "SGP",
        "city": "Singapore",
        "track_length_km": 4.940,
        "turns": 19,
        "drs_zones": 3,
        "first_gp_year": 2008,
        "lap_record_time": "1:35.867",
        "lap_record_driver": "Lewis Hamilton",
        "lap_record_year": 2023,
        "latitude": 1.2914,
        "longitude": 103.8644,
    },
    {
        "circuit_key": 64,
        "circuit_short_name": "Austin",
        "circuit_full_name": "Circuit of the Americas",
        "country_name": "United States",
        "country_code": "USA",
        "city": "Austin",
        "track_length_km": 5.513,
        "turns": 20,
        "drs_zones": 2,
        "first_gp_year": 2012,
        "lap_record_time": "1:36.169",
        "lap_record_driver": "Charles Leclerc",
        "lap_record_year": 2019,
        "latitude": 30.1328,
        "longitude": -97.6411,
    },
    {
        "circuit_key": 65,
        "circuit_short_name": "Mexico City",
        "circuit_full_name": "Autódromo Hermanos Rodríguez",
        "country_name": "Mexico",
        "country_code": "MEX",
        "city": "Mexico City",
        "track_length_km": 4.304,
        "turns": 17,
        "drs_zones": 3,
        "first_gp_year": 1963,
        "lap_record_time": "1:17.774",
        "lap_record_driver": "Valtteri Bottas",
        "lap_record_year": 2021,
        "latitude": 19.4042,
        "longitude": -99.0907,
    },
    {
        "circuit_key": 66,
        "circuit_short_name": "Interlagos",
        "circuit_full_name": "Autódromo José Carlos Pace",
        "country_name": "Brazil",
        "country_code": "BRA",
        "city": "São Paulo",
        "track_length_km": 4.309,
        "turns": 15,
        "drs_zones": 2,
        "first_gp_year": 1973,
        "lap_record_time": "1:10.540",
        "lap_record_driver": "Valtteri Bottas",
        "lap_record_year": 2018,
        "latitude": -23.7036,
        "longitude": -46.6997,
    },
    {
        "circuit_key": 67,
        "circuit_short_name": "Las Vegas",
        "circuit_full_name": "Las Vegas Strip Circuit",
        "country_name": "United States",
        "country_code": "USA",
        "city": "Las Vegas",
        "track_length_km": 6.201,
        "turns": 17,
        "drs_zones": 2,
        "first_gp_year": 2023,
        "lap_record_time": "1:35.490",
        "lap_record_driver": "Oscar Piastri",
        "lap_record_year": 2023,
        "latitude": 36.1147,
        "longitude": -115.1728,
    },
    {
        "circuit_key": 68,
        "circuit_short_name": "Lusail",
        "circuit_full_name": "Lusail International Circuit",
        "country_name": "Qatar",
        "country_code": "QAT",
        "city": "Lusail",
        "track_length_km": 5.419,
        "turns": 16,
        "drs_zones": 2,
        "first_gp_year": 2021,
        "lap_record_time": "1:24.319",
        "lap_record_driver": "Max Verstappen",
        "lap_record_year": 2023,
        "latitude": 25.4900,
        "longitude": 51.4542,
    },
    {
        "circuit_key": 69,
        "circuit_short_name": "Yas Marina",
        "circuit_full_name": "Yas Marina Circuit",
        "country_name": "Abu Dhabi",
        "country_code": "UAE",
        "city": "Abu Dhabi",
        "track_length_km": 5.281,
        "turns": 16,
        "drs_zones": 2,
        "first_gp_year": 2009,
        "lap_record_time": "1:26.103",
        "lap_record_driver": "Max Verstappen",
        "lap_record_year": 2021,
        "latitude": 24.4672,
        "longitude": 54.6031,
    },
]

# COMMAND ----------

# Supabase 적재용 SQL 생성
# Supabase SQL Editor에서 직접 실행하거나
# psycopg2/asyncpg로 프로그래밍 방식으로 적재 가능

for c in circuits_data:
    cols = ", ".join(c.keys())
    vals = []
    for v in c.values():
        if v is None:
            vals.append("NULL")
        elif isinstance(v, str):
            vals.append(f"'{v}'")
        else:
            vals.append(str(v))
    vals_str = ", ".join(vals)
    print(f"INSERT INTO circuits ({cols}) VALUES ({vals_str}) ON CONFLICT (circuit_key) DO UPDATE SET circuit_full_name = EXCLUDED.circuit_full_name, track_length_km = EXCLUDED.track_length_km, turns = EXCLUDED.turns, drs_zones = EXCLUDED.drs_zones, lap_record_time = EXCLUDED.lap_record_time, lap_record_driver = EXCLUDED.lap_record_driver, lap_record_year = EXCLUDED.lap_record_year;")

print(f"\n-- Total: {len(circuits_data)} circuits inserted/updated")
